In [1]:
import numpy as np

# Given matrix A
A = np.array([[1, 2, 0, 2, 1],
              [3, 6, 1, 9, 6],
              [2, 4, 1, 7, 5]])
U, S, Vt = np.linalg.svd(A)



In [6]:
print(S)

[16.33322517  1.10713843  0.        ]


In [7]:
rank = np.sum(S > 1e-10)
print(rank)

2


In [4]:
basis_col_space = U[:, :rank]
n = A.shape[1]
basis_null_space = Vt[rank:, :].T
basis_row_space = Vt[:rank, :].T
m = A.shape[0]
basis_left_null_space = U[:, rank:]


In [5]:
print("Rank of A:", rank)
print("Basis for column space:\n", basis_col_space)
print("Basis for null space:\n", basis_null_space)
print("Basis for row space:\n", basis_row_space)
print("Basis for left null space:\n", basis_left_null_space)

Rank of A: 2
Basis for column space:
 [[-0.18595863  0.7950384 ]
 [-0.78150277  0.2364743 ]
 [-0.59554413 -0.5585641 ]]
Basis for null space:
 [[-0.07707193 -0.75827202 -0.4947439 ]
 [ 0.26585773  0.13010215  0.46383768]
 [ 0.93512799 -0.10590067 -0.15025835]
 [-0.14293421  0.46276749 -0.48301757]
 [-0.16877512 -0.42746727  0.53310369]]
Basis for row space:
 [[-0.22785183  0.34985064]
 [-0.45570365  0.69970128]
 [-0.08430955 -0.29092098]
 [-0.70863231 -0.17306167]
 [-0.48078048 -0.52291231]]
Basis for left null space:
 [[ 0.57735027]
 [-0.57735027]
 [ 0.57735027]]
